import {food} from './app/shared/models/food';

export const sample_food: food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Dosa',
    price: 4,
    cookTime: '10-15',
    favorite: false,
    origins: ['india'],
    stars: 4,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Dosa'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Biryani',
    price: 10,
    cookTime: '50-60',
    favorite: true,
    origins: ['india' , 'asia'],
    stars: 5,
    imageUrl: 'assets/food-6.jpg',
    tags: ['SlowFood', 'Biryani', 'Lunch'],
  },
  {
    id:'7',
    name: 'Pasta',
    price: 10,
    cookTime: '20-25',
    favorite: false,
    origins: ['italy'],
    stars: 3,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Pasta'],
  },
  {
    id:'8',
    name: 'Sandwich',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['england', 'us'],
    stars: 3,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Sandwich'],
  },
  {
    id:'9',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: true,
    origins: ['germany', 'us'],
    stars: 4,
    imageUrl: 'assets/food-9.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
]


